services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    env_file: ".env"
    restart: always
    ports:
      - ${MOSQUITTO_PORT}:1883
      - ${MOSQUITTO_WS_PORT}:2883
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  mqttx:
    image: emqx/mqttx-web
    container_name: mqttx-web
    ports:
      - ${MQTTX_PORT}:80

  db:
    image: postgres:18
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=acs
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4:9
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - db

volumes:
  postgres_data: