services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    env_file: ".env"
    restart: always
    ports:
      - ${MOSQUITTO_PORT}:1883
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  mqttx:
    image: emqx/mqttx-web
    container_name: mqttx-web
    ports:
      - ${MQTTX_PORT}:80
