spring:
  application:
    name: acs-backend
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    locations: classpath:/db/migration
    schemas: employees
    baselineOnMigrate: true
    enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/acs
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

server:
  port: ${SPRING_PORT}